import { stripActionMetadataFileFromCustomFields } from "@/utils/actions";
import { WINDOWS_NEWLINE } from "@/utils/environment";
import { FileNotFoundError } from "@/utils/errors";
import { basename } from "node:path";

const ACTION_METADATA_TEMPLATE_FILE = "./action.template.yml";
const ACTION_METADATA_FILE = "./action.yml";

const OPTIONS: PostbuildOptions = {
    sourceFileName: basename(ACTION_METADATA_TEMPLATE_FILE),
    encoding: "utf8",
    generateAutoGeneratedWarningMessage: true,
    removeTemplateOnlyFields: true,
    newline: WINDOWS_NEWLINE,
    lineWidth: 80,
};

type PostbuildOptions = Exclude<
    & Parameters<typeof stripActionMetadataFileFromCustomFields>[2],
    string
>;

FileNotFoundError.throwIfNotFound(ACTION_METADATA_FILE);

await stripActionMetadataFileFromCustomFields(ACTION_METADATA_FILE, ACTION_METADATA_FILE, OPTIONS);
